import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import CoverParticles from "@/components/cover-particles";
import Typer from "@/components/typingAnimation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="backdrop-blur-sm size-full  h-96">
          <CoverParticles />
          <NavBar />
        </section>
        {children}
        </body>
    </html>
  );
}
