import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import CoverParticles from "@/components/cover-particles";
import Typer from "@/components/typingAnimation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="backdrop-blur-sm size-full  h-96">
          <CoverParticles />
          <NavBar />
          <div className="flex w-[100%] -translate-y-6 max-w-[800px] m-auto relative">
            <div className="flex w-40  justify-center">
              <iframe src="https://giphy.com/embed/g5nbfmiZQAjihMx4Oi" className="pointer-events-none" allowFullScreen></iframe>
              <div className="opacity-0">
                  <Typer descriptions={[ "","*****"]} speed={50} intervalo={1200}/>
              </div>
            </div>
          </div>
        </section>
        {children}
        </body>
    </html>
  );
}
